<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Reports Summary</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .text-right {
            text-align: right;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>
    <h2>Reports</h2>
    <table>
        <thead>
            <tr>
                <th>Report #</th>
                <th>Period</th>
                <th>Generated By</th>
                <th class="text-right">Transactions</th>
                <th class="text-right">Total Sales</th>
                <th class="text-right">Tax</th>
                <th class="text-right">Discounts</th>
                <th class="text-right">Cash</th>
                <th>Currency</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
            <tr>
                <td>{{ $report->id }}</td>
                <td>
                    {{ $report->start_datetime }}<br>
                    to<br>
                    {{ $report->end_datetime }}
                </td>
                <td>{{ $report->user->name }}</td>
                <td class="text-right">{{ $report->transaction_count }}</td>
                <td class="text-right">{{ number_format($report->total_sales, 2) }} {{ $report->currency->symbol }}</td>
                <td class="text-right">{{ number_format($report->total_tax, 2) }}</td>
                <td class="text-right">{{ number_format($report->total_discounts, 2) }}</td>
                <td class="text-right">{{ number_format($report->cash_amount, 2) }}</td>
                <td>{{ $report->currency->code }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>