<script>
    // Z Report
    async function generateZReport() {
        const btn = document.getElementById("z_report");
        const text = document.getElementById("z_report_text");
        const spinner = document.getElementById("z_report_loading");

        btn.classList.add("disabled");
        text.classList.add("d-none");
        spinner.classList.remove("d-none");

        try {
            const response = await fetch("{{ route('reports.create') }}", {
                method: "POST",
                headers: {
                    "X-CSRF-TOKEN": document.querySelector(
                        'meta[name="csrf-token"]'
                    ).content,
                    "Content-Type": "application/json",
                },
            });

            if (!response.ok) throw new Error("Failed to generate report");

            const { report } = await response.json();

            await printZReport(report);

            Swal.fire({
                icon: "success",
                title: "Z Report Generated",
                text: "Shift closed successfully",
            });
        } catch (error) {
            console.error("Error:", error);
            Swal.fire({
                icon: "error",
                title: "Failed",
                text: error.message || "Could not generate Z Report",
            });
        } finally {
            btn.classList.remove("disabled");
            text.classList.remove("d-none");
            spinner.classList.add("d-none");
        }
    }

    function printZReport(report) {
        const reportWindow = window.open("", "", "width=300,height=500");

        if (!reportWindow) {
            console.error(
                "Failed to open receipt window. Check popup blocker settings."
            );
            return;
        }

        reportWindow.document.write(this.getReportHtml(report));
        reportWindow.document.close();

        reportWindow.onload = () => {
            reportWindow.print();
            reportWindow.close();
        };
    }

    function formatCurrency(amount, currency) {
        return currency.symbol + amount.toFixed(2);
    }

    function getReportHtml(report) {
        return `
            <!DOCTYPE html>
            <html>
                <head>
                    <title>Z Report #${report.id}</title>
                    <style>
                        body { font-family: Arial, sans-serif; font-size: 12px; }
                        .header { text-align: center; margin-bottom: 10px; }
                        .title { font-weight: bold; font-size: 16px; }
                        .subtitle { font-size: 14px; margin-bottom: 5px; }
                        .divider { border-top: 1px dashed #000; margin: 5px 0; }
                        table { width: 100%; border-collapse: collapse; }
                        td { padding: 2px 0; }
                        .right { text-align: right; }
                        .bold { font-weight: bold; }
                        .center { text-align: center; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <div class="title">Khrabish</div>
                        <div class="subtitle">Z REPORT #${report.id}</div>
                        <div>${new Date(report.created_at).toLocaleString()}</div>
                    </div>

                    <div class="divider"></div>
                    <table>
                        <tr>
                            <td>Period:</td>
                            <td class="right">
                                ${new Date(
                                    report.start_datetime
                                ).toLocaleTimeString()} -
                                ${new Date(
                                    report.end_datetime
                                ).toLocaleTimeString()}
                            </td>
                        </tr>
                        <tr>
                            <td>Generated By:</td>
                            <td class="right">${report.user.name}</td>
                        </tr>
                    </table>
                    <div class="divider"></div>
                    <table>
                        <tr>
                            <td>Total Transactions:</td>
                            <td class="right">${report.transaction_count}</td>
                        </tr>
                        <tr>
                            <td>Total Sales:</td>
                            <td class="right">${formatCurrency(
                                report.total_sales,
                                report.currency
                            )}</td>
                        </tr>
                        <tr>
                            <td>Total Tax:</td>
                            <td class="right">${formatCurrency(
                                report.total_tax,
                                report.currency
                            )}</td>
                        </tr>
                        <tr>
                            <td>Total Discounts:</td>
                            <td class="right">${formatCurrency(
                                report.total_discounts,
                                report.currency
                            )}</td>
                        </tr>
                        <tr>
                            <td>Cash Amount:</td>
                            <td class="right">${formatCurrency(
                                report.cash_amount,
                                report.currency
                            )}</td>
                        </tr>
                        <tr class="bold">
                            <td>Net Sales:</td>
                            <td class="right">
                                ${formatCurrency(
                                    report.total_sales - report.total_discounts,
                                    report.currency
                                )}
                            </td>
                        </tr>
                    </table>
                    <div class="divider"></div>
                    <div class="center">*** SHIFT CLOSED ***</div>
                    <div class="center">${new Date().toLocaleString()}</div>
                </body>
            </html>
        `;
    }
</script>